### ISSUE TITLE
Question - Stream playback quality values

### ISSUE THREAD

**Issue by JFazio13** [tonywagner/plugin.video.mlb#4]
In get_playback in account.py, the quality value is set to PLACEHOLDER, which seems to function like adaptive in the old mlbserver. Do we know what the other enum values are if we wanted to force high quality for example? I've tried a bunch of different values, but the API responds with "Variable 'quality' has an invalid value: Invalid input for Enum 'PlaybackQuality'. No value found for name 'HIGH'" for all the values I've tried.

**Comment by tonywagner** [comment]
I am not sure what that option does.

The place where we can force the quality will be in the proxy_file function. It’s on my list to re-implement.

**Comment by tonywagner** [comment]
The "resolution" URL parameter has been added in https://github.com/tonywagner/plugin.video.mlb/commit/69e06c81e697b8e1be93453aeeeea14cfbf378eb

Just add "&resolution=best" or "&resolution=720p60" or "&resolution=360" etc. to the end of any video page.

More coming...
