### ISSUE TITLE
Stateful/bound config folder for Docker

### ISSUE THREAD

**Issue by ahughes03** [tonywagner/plugin.video.mlb#5]
Hi there, would it be possible to allow for config data/logins to be stored via a bind mounted folder for the docker container? I'd prefer to have those exposed and stored like most other docker containers. I tried exposing the data folder but ran into the following error:

```
    volumes:
      - /opt/appdata/mlbplugin:/plugin.video.mlb/data

```
```
Traceback (most recent call last):
  File "/plugin.video.mlb/service.py", line 2, in <module>
    from resources.lib.server import Server
  File "/plugin.video.mlb/resources/lib/server.py", line 13, in <module>
    import resources.lib.utils as utils
  File "/plugin.video.mlb/resources/lib/utils.py", line 239, in <module>
    LOCAL_WEBSERVER_PORT = int(get_setting('local_webserver_port'))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

I'm guessing I exposed things wrong, because it seems like the service script can't import the WEBSERVER_PORT, which is now stored outside of the container...

**Comment by SethL** [comment]
Could it be permissions?  I have mine set similar and it works fine without that error (well the container doesn't work for me but I believe that is a separate issue.  the xml file persists.. 
    volumes:
     - video_mlb_data1:/plugin.video.mlb/data/  

I created the volume in portainer and then referenced it in the stacks config...

**Comment by ahughes03** [comment]
Interesting. My container spins up, but then gets stuck with that error message and then I can’t navigate to the web server. I tried nuking the external folder (I’m only wanting to bind mount, not use a volume generated via portioner if I can avoid it) but that didn’t seem to do anything different. 

It’s my understanding that generating a volume in Portainer maps the volume to /var/lib/docker/volumes, and I’m trying to keep my configs organized in /opt (it’s just how I’ve always organized things).

**Comment by tonywagner** [comment]
Should be fixed in https://github.com/tonywagner/plugin.video.mlb/commit/e598978651e10bace5dc0b0e6a8847b872d99f84

**Comment by ahughes03** [comment]
Confirmed the fix, thanks!!!
