### ISSUE TITLE
Cannot login outside of United States

### ISSUE THREAD

**Issue by mooninite** [tonywagner/plugin.video.mlb#6]
When I attempt to use this plugin from outside of the United States I cannot login. I get an error from the MLB API. When I VPN into the US I can login. I get different IPs for the MLB API based on location. Is this a known issue? MLB not allowing this new API from non-US locations?

The old MLB.TV plugin worked from outside the US with the old API.

Example login result from Canada:

```
failed to get interaction_handle Expecting value: line 2 column 1 (char 1)

<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>403 Forbidden</title>
  </head>
  <body>
    <h1>Error 403 Forbidden</h1>
    <p>Forbidden</p>
    <h3>Error 54113</h3>
    <p>Details: cache-yyz4542-YYZ 1721528275 3586972605</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

**Comment by tonywagner** [comment]
Are you actually in Canada?

Can you log in and watch at mlb.com on the same computer/network?

**Comment by mooninite** [comment]
It appears to be a problem with the login API. The login API blocks non-US attempts? I get the same 403 error from Varnish when I use Firefox and visit https://www.mlb.com/login and look at the Developer Tools / Network tab.

Using Firefox I tried to login to the home page https://www.mlb.com but the login box gives me an error. I VPN into the US and I can login. I disconnect from the VPN and I can stream any game. Video streaming works as expected. Full HD picture, sound, etc.

This is all new... I could login without a problem in the past. So, sure this is not a bug with this plugin, but I don't know if MLB knows about this or if they are just going to block non-US people now.

**Comment by mooninite** [comment]
OK, the MLB may be blocking specific configurations. I was able to get it working so it is probably isolated to just me. Closing.
